// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdvtdickayikxdrjukne.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kdnRkaWNrYXlpa3hkcmp1a25lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MjE3NzgsImV4cCI6MjA3MzQ5Nzc3OH0.RcYLVL6tq2neL53ng6fcroCY32SWmcorg1jSFS-HcTg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});